# 项目名
name: dumi book test

# 只有在master分支发生push事件时触发
on:
  push:
    branches:
      - master
deploy:
  type: git
  repo: git@github.com:racheljoin/pop.git
  brach: master

# 工作流
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境

    steps:
      # 拉代码
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          type: git
          repo: git@github.com:racheljoin/pop.git
          branch: build # 打包的内容放到build分支下
          folder: docs-dist
